name: Deploy to EC2 (Manual)

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to EC2 Instance
    runs-on: ubuntu-latest

    steps:
      - name: SSH into EC2 and Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            export POETRY_PATH="/home/ubuntu/.local/bin/poetry"

            cd /home/ubuntu/jesafe

            echo "Pulling latest code..."
            git checkout main
            export GIT_TERMINAL_PROMPT=0 
            git pull origin main

            echo "Creating .env file..."
            echo '${{ secrets.ENV_FILE_CONTENT }}' > .env

            echo "Installing Python dependencies..."
            $POETRY_PATH install --no-root

            echo "Starting PostgreSQL container..."
            docker compose up -d

            echo "Restarting FastAPI application with PM2..."
            pm2 reload jesafe-api || pm2 start "$POETRY_PATH run uvicorn src.main:app --host 0.0.0.0 --port 8000" --name jesafe-api

            echo "Deployment successful!"